name: learn_english
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # font and icon
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  overlay_support: ^1.0.3
  fluttertoast: ^3.1.3
  google_fonts: ^0.4.0

  # animation
  animated_text_kit: ^2.0.0
  flutter_sequence_animation: "^3.0.0"
  sa_anicoto: ^1.0.0
  auto_size_text: ^2.1.0
  dots_indicator: ^1.0.0
  percent_indicator: ^2.1.3
  smooth_page_indicator: ^0.1.5
  page_transition: ^1.1.5
  flip_panel: ^1.0.1
  liquid_swipe: ^1.4.3
  scrollable_positioned_list: ^0.1.6
  flip_card: ^0.4.4
  
  path_provider: ^1.6.7
  path: ^1.7.0

  # firebase dependence
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.0
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.13.4+1
  firebase_auth_web: ^0.1.2
  

  # auth dependence
  google_sign_in: ^4.0.11
  google_sign_in_web: ^0.9.1+1
  flutter_facebook_login: ^3.0.0

  #state management
  provider: ^4.0.4

  #record voice
  speech_to_text: ^1.1.0
  google_speech: ^1.0.2
  
  #audio
  audioplayers: ^0.15.1
  flutter_tts: ^1.2.0
  

  #access permission
  permission_handler: ^4.4.0+hotfix.2
  shared_preferences: ^0.5.7+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.7

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
